// <auto-generated />
namespace GerenciadorProcessos.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class incluindoointApiCaptchanoparametro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(incluindoointApiCaptchanoparametro));
        
        string IMigrationMetadata.Id
        {
            get { return "202004231430084_incluindo o int ApiCaptcha no parametro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
