// <auto-generated />
namespace GerenciadorProcessos.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class iniciandoobancodedados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iniciandoobancodedados));
        
        string IMigrationMetadata.Id
        {
            get { return "202001282231545_iniciando o banco de dados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
